const API_BASE_URL_DEVELOPMENT = 'https://localhost:7019/api';
const API_BASE_URL_PRODUCTION = 'https://backoffice-murilo.azurewebsites.net/api';
const VIA_CEP_API = 'https://viacep.com.br/ws/';


const PESSOAS_ENDPOINTS = 'pessoas';
const ENDERECOS_ENDPOINST = 'enderecos';
const DEPARTAMENTOS_ENDPOINST = 'departamentos';

const Development = {

    API_GET_CEP: `${VIA_CEP_API}`,

    API_GET_ALL_PESSOAS: `${API_BASE_URL_DEVELOPMENT}/${PESSOAS_ENDPOINTS}`,
    API_GET_PESSOA_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${PESSOAS_ENDPOINTS}/`,
    API_CREATE_PESSOA: `${API_BASE_URL_DEVELOPMENT}/${PESSOAS_ENDPOINTS}`,
    API_UPDATE_PESSOA: `${API_BASE_URL_DEVELOPMENT}/${PESSOAS_ENDPOINTS}/`,
    API_DELETE_PESSOA: `${API_BASE_URL_DEVELOPMENT}/${PESSOAS_ENDPOINTS}/`,

    API_GET_ENDERECO_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDERECOS_ENDPOINST}/`,
    API_CREATE_ENDERECO: `${API_BASE_URL_DEVELOPMENT}/${ENDERECOS_ENDPOINST}`,
    API_UPDATE_ENDERECO: `${API_BASE_URL_DEVELOPMENT}/${ENDERECOS_ENDPOINST}/`,
    API_DELETE_ENDERECO: `${API_BASE_URL_DEVELOPMENT}/${ENDERECOS_ENDPOINST}/`,

    API_GET_ALL_DEPARTAMENTOS: `${API_BASE_URL_DEVELOPMENT}/${DEPARTAMENTOS_ENDPOINST}`,
    API_GET_DEPARTAMENTO_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${DEPARTAMENTOS_ENDPOINST}/`,
    API_CREATE_DEPARTAMENTO: `${API_BASE_URL_DEVELOPMENT}/${DEPARTAMENTOS_ENDPOINST}`,
    API_UPDATE_DEPARTAMENTO: `${API_BASE_URL_DEVELOPMENT}/${DEPARTAMENTOS_ENDPOINST}/`,
    API_DELETE_DEPARTAMENTO: `${API_BASE_URL_DEVELOPMENT}/${DEPARTAMENTOS_ENDPOINST}/`,
    
};

const Production = {
    
    API_GET_CEP: `${VIA_CEP_API}`,

    API_GET_ALL_PESSOAS: `${API_BASE_URL_PRODUCTION}/${PESSOAS_ENDPOINTS}`,
    API_GET_PESSOA_BY_ID: `${API_BASE_URL_PRODUCTION}/${PESSOAS_ENDPOINTS}/`,
    API_CREATE_PESSOA: `${API_BASE_URL_PRODUCTION}/${PESSOAS_ENDPOINTS}`,
    API_UPDATE_PESSOA: `${API_BASE_URL_PRODUCTION}/${PESSOAS_ENDPOINTS}/`,
    API_DELETE_PESSOA: `${API_BASE_URL_PRODUCTION}/${PESSOAS_ENDPOINTS}/`,

    API_GET_ENDERECO_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDERECOS_ENDPOINST}/`,
    API_CREATE_ENDERECO: `${API_BASE_URL_PRODUCTION}/${ENDERECOS_ENDPOINST}`,
    API_UPDATE_ENDERECO: `${API_BASE_URL_PRODUCTION}/${ENDERECOS_ENDPOINST}/`,
    API_DELETE_ENDERECO: `${API_BASE_URL_PRODUCTION}/${ENDERECOS_ENDPOINST}/`,

    API_GET_ALL_DEPARTAMENTOS: `${API_BASE_URL_PRODUCTION}/${DEPARTAMENTOS_ENDPOINST}`,
    API_GET_DEPARTAMENTO_BY_ID: `${API_BASE_URL_PRODUCTION}/${DEPARTAMENTOS_ENDPOINST}/`,
    API_CREATE_DEPARTAMENTO: `${API_BASE_URL_PRODUCTION}/${DEPARTAMENTOS_ENDPOINST}`,
    API_UPDATE_DEPARTAMENTO: `${API_BASE_URL_PRODUCTION}/${DEPARTAMENTOS_ENDPOINST}/`,
    API_DELETE_DEPARTAMENTO: `${API_BASE_URL_PRODUCTION}/${DEPARTAMENTOS_ENDPOINST}/`,

};

const Constants = process.env.NODE_ENV === 'development' ? Development : Production;

export default Constants;